version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: instagram-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instagram_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest

    container_name: instagram-dynamodb-local

    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

    ports:
      - "8100:8000"

volumes:
  postgres_data: